# Generated by Django 4.2.4 on 2023-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
