# Generated by Django 4.2.4 on 2023-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_seller_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sell',
            field=models.ManyToManyField(related_name='transaction', to='transaction.sell'),
        ),
    ]
