# Generated by Django 4.2.4 on 2023-08-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sell',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.sell'),
            preserve_default=False,
        ),
    ]
