# Generated by Django 4.2.4 on 2023-08-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_transaction_sell_transaction_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.sell'),
        ),
    ]
