# Generated by Django 4.2.4 on 2023-08-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sell',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.customer'),
        ),
    ]
