# Generated by Django 4.2.4 on 2023-08-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transaction_slug_alter_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(),
        ),
    ]
