# Generated by Django 4.2.4 on 2023-08-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='slug',
        ),
    ]
