# Generated by Django 4.2.4 on 2023-08-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_remove_transaction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
