# Generated by Django 4.2.4 on 2023-08-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_seller_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
