# Generated by Django 4.2.4 on 2023-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_remove_transaction_customer_remove_transaction_sell_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='sell',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='customer',
        ),
        migrations.AddField(
            model_name='sell',
            name='phone_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
