# Generated by Django 4.2.4 on 2023-09-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_rename_sell_sell_amount_remove_sell_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='difference',
            field=models.FloatField(default=0),
        ),
    ]
