# Generated by Django 4.2.4 on 2023-09-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_sell_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='difference',
        ),
        migrations.AddField(
            model_name='seller',
            name='difference',
            field=models.FloatField(default=0),
        ),
    ]
